Run started:2024-04-24 13:10:31.873821

Test results:
>> Issue: [B404:blacklist] Consider possible security implications associated with the subprocess module.
   Severity: Low   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.7.8/blacklists/blacklist_imports.html#b404-import-subprocess
   Location: ./../res_files/Neutron/openstack%2Fneutron~master~I985bafb44c131d6013961eb12bdbd103b6b6469a_2_neutron%2Ftests%2Ftempest%2Fscenario%2Ftest_routed_networks.py/test_routed_networks_new-021ac7c4ab1c2af41dcb78da754b7faa.py:15:0
14	#    under the License.
15	import subprocess
16	import time

--------------------------------------------------
>> Issue: [B108:hardcoded_tmp_directory] Probable insecure usage of temp file/directory.
   Severity: Medium   Confidence: Medium
   CWE: CWE-377 (https://cwe.mitre.org/data/definitions/377.html)
   More Info: https://bandit.readthedocs.io/en/1.7.8/plugins/b108_hardcoded_tmp_directory.html
   Location: ./../res_files/Neutron/openstack%2Fneutron~master~I985bafb44c131d6013961eb12bdbd103b6b6469a_2_neutron%2Ftests%2Ftempest%2Fscenario%2Ftest_routed_networks.py/test_routed_networks_new-021ac7c4ab1c2af41dcb78da754b7faa.py:117:24
116	        ret = 1
117	        key_file_path = '/tmp/testkey.dat'
118	        ssh_commands = 'ssh -o UserKnownHostsFile=/dev/null -o ' \

--------------------------------------------------
>> Issue: [B602:subprocess_popen_with_shell_equals_true] subprocess call with shell=True identified, security issue.
   Severity: High   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.7.8/plugins/b602_subprocess_popen_with_shell_equals_true.html
   Location: ./../res_files/Neutron/openstack%2Fneutron~master~I985bafb44c131d6013961eb12bdbd103b6b6469a_2_neutron%2Ftests%2Ftempest%2Fscenario%2Ftest_routed_networks.py/test_routed_networks_new-021ac7c4ab1c2af41dcb78da754b7faa.py:127:18
126	        for i in range(0, retries):
127	            ret = subprocess.call(all_cmd, shell=True,
128	                                  stdout=subprocess.PIPE,
129	                                  stderr=subprocess.STDOUT)
130	            if ret == 0:

--------------------------------------------------
>> Issue: [B602:subprocess_popen_with_shell_equals_true] subprocess call with shell=True identified, security issue.
   Severity: High   Confidence: High
   CWE: CWE-78 (https://cwe.mitre.org/data/definitions/78.html)
   More Info: https://bandit.readthedocs.io/en/1.7.8/plugins/b602_subprocess_popen_with_shell_equals_true.html
   Location: ./../res_files/Neutron/openstack%2Fneutron~master~I985bafb44c131d6013961eb12bdbd103b6b6469a_2_neutron%2Ftests%2Ftempest%2Fscenario%2Ftest_routed_networks.py/test_routed_networks_new-021ac7c4ab1c2af41dcb78da754b7faa.py:134:8
133	
134	        subprocess.call('rm -f %s' % key_file_path, shell=True,
135	                        stdout=subprocess.PIPE)
136	        self.assertEqual(0, ret, 'instance is down')

--------------------------------------------------

Code scanned:
	Total lines of code: 176
	Total lines skipped (#nosec): 0
	Total potential issues skipped due to specifically being disabled (e.g., #nosec BXXX): 0

Run metrics:
	Total issues (by severity):
		Undefined: 0
		Low: 1
		Medium: 1
		High: 2
	Total issues (by confidence):
		Undefined: 0
		Low: 0
		Medium: 1
		High: 3
Files skipped (0):
